/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExpertDashboardRouteImport } from './routes/expert-dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClinicalSourcesRouteImport } from './routes/clinical-sources'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSimulatorRouteImport } from './routes/_app.simulator'
import { Route as AppScannerRouteImport } from './routes/_app.scanner'
import { Route as AppReportRouteImport } from './routes/_app.report'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppExpertReviewRouteImport } from './routes/_app.expert-review'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAssessmentRouteImport } from './routes/_app.assessment'
import { Route as AppActionPlanRouteImport } from './routes/_app.action-plan'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertDashboardRoute = ExpertDashboardRouteImport.update({
  id: '/expert-dashboard',
  path: '/expert-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalSourcesRoute = ClinicalSourcesRouteImport.update({
  id: '/clinical-sources',
  path: '/clinical-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSimulatorRoute = AppSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppExpertReviewRoute = AppExpertReviewRouteImport.update({
  id: '/expert-review',
  path: '/expert-review',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentRoute = AppAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AppRoute,
} as any)
const AppActionPlanRoute = AppActionPlanRouteImport.update({
  id: '/action-plan',
  path: '/action-plan',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clinical-sources': typeof ClinicalSourcesRoute
  '/contact': typeof ContactRoute
  '/expert-dashboard': typeof ExpertDashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/action-plan': typeof AppActionPlanRoute
  '/assessment': typeof AppAssessmentRoute
  '/dashboard': typeof AppDashboardRoute
  '/expert-review': typeof AppExpertReviewRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/report': typeof AppReportRoute
  '/scanner': typeof AppScannerRoute
  '/simulator': typeof AppSimulatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clinical-sources': typeof ClinicalSourcesRoute
  '/contact': typeof ContactRoute
  '/expert-dashboard': typeof ExpertDashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/action-plan': typeof AppActionPlanRoute
  '/assessment': typeof AppAssessmentRoute
  '/dashboard': typeof AppDashboardRoute
  '/expert-review': typeof AppExpertReviewRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/report': typeof AppReportRoute
  '/scanner': typeof AppScannerRoute
  '/simulator': typeof AppSimulatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/clinical-sources': typeof ClinicalSourcesRoute
  '/contact': typeof ContactRoute
  '/expert-dashboard': typeof ExpertDashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/_app/action-plan': typeof AppActionPlanRoute
  '/_app/assessment': typeof AppAssessmentRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expert-review': typeof AppExpertReviewRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/report': typeof AppReportRoute
  '/_app/scanner': typeof AppScannerRoute
  '/_app/simulator': typeof AppSimulatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clinical-sources'
    | '/contact'
    | '/expert-dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/action-plan'
    | '/assessment'
    | '/dashboard'
    | '/expert-review'
    | '/profile'
    | '/progress'
    | '/report'
    | '/scanner'
    | '/simulator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clinical-sources'
    | '/contact'
    | '/expert-dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/action-plan'
    | '/assessment'
    | '/dashboard'
    | '/expert-review'
    | '/profile'
    | '/progress'
    | '/report'
    | '/scanner'
    | '/simulator'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/clinical-sources'
    | '/contact'
    | '/expert-dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/_app/action-plan'
    | '/_app/assessment'
    | '/_app/dashboard'
    | '/_app/expert-review'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/report'
    | '/_app/scanner'
    | '/_app/simulator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  ClinicalSourcesRoute: typeof ClinicalSourcesRoute
  ContactRoute: typeof ContactRoute
  ExpertDashboardRoute: typeof ExpertDashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert-dashboard': {
      id: '/expert-dashboard'
      path: '/expert-dashboard'
      fullPath: '/expert-dashboard'
      preLoaderRoute: typeof ExpertDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical-sources': {
      id: '/clinical-sources'
      path: '/clinical-sources'
      fullPath: '/clinical-sources'
      preLoaderRoute: typeof ClinicalSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/simulator': {
      id: '/_app/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof AppSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scanner': {
      id: '/_app/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expert-review': {
      id: '/_app/expert-review'
      path: '/expert-review'
      fullPath: '/expert-review'
      preLoaderRoute: typeof AppExpertReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessment': {
      id: '/_app/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AppAssessmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/action-plan': {
      id: '/_app/action-plan'
      path: '/action-plan'
      fullPath: '/action-plan'
      preLoaderRoute: typeof AppActionPlanRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActionPlanRoute: typeof AppActionPlanRoute
  AppAssessmentRoute: typeof AppAssessmentRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpertReviewRoute: typeof AppExpertReviewRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppReportRoute: typeof AppReportRoute
  AppScannerRoute: typeof AppScannerRoute
  AppSimulatorRoute: typeof AppSimulatorRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActionPlanRoute: AppActionPlanRoute,
  AppAssessmentRoute: AppAssessmentRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpertReviewRoute: AppExpertReviewRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppReportRoute: AppReportRoute,
  AppScannerRoute: AppScannerRoute,
  AppSimulatorRoute: AppSimulatorRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  ClinicalSourcesRoute: ClinicalSourcesRoute,
  ContactRoute: ContactRoute,
  ExpertDashboardRoute: ExpertDashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
